name: Bug Report
description: Use this template to report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the following fields.
  - type: textarea
    id: describe_the_bug
    attributes:
      label: Describe the Bug
      placeholder: Give a clear and concise description of what the bug is
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      placeholder: What version of the plugin is being used?
    validations:
      required: true
  - type: dropdown
    id: server_loader
    attributes:
      label: Select the Server Loader
      options:
        - Paper
        - Spigot
        - Folia
        - Purpur
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Describe the steps to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: Describe what you expected to happen
    validations:
      required: false
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      options:
        - Low
        - Medium
        - High
